github/erblint-github

README.md, docs/rules/accessibility/image-has-alt.md, docs/rules/accessibility/no-redundant-image-alt.md, lib/erblint-github/linters/github/accessibility/image_has_alt.rb, test/linters/accessibility/image_has_alt_test.rb
Closes https://github.com/github/erblint-github/issues/1
- Adds `GitHub::Accessibility::ImageHasAlt`. When enabled, this rule will raise a lint error if an `img` tag is found without an `alt` attribute set. The `alt` attribute must be set to an empty string if the image is decorative, or a string that describes either the image, or the functional use. 
- Adds better documentation of lint rules, inspired by [eslint-plugin-github](https://github.com/github/eslint-plugin-github/).
=> Add `image-has-alt` and better documentation of rules

README.md, docs/rules/accessibility/no-aria-label-misuse.md, lib/erblint-github/linters/github/accessibility/no_aria_label_misuse.rb, test/linters/accessibility/no_aria_label_misuse_test.rb
Relates to https://github.com/github/accessibility/issues/430
This PR introduces a linter rule to prevent misuse of `aria-label` and `aria-labelledby`. For more information, see [no-aria-label-misuse.md](https://github.com/github/erblint-github/blob/8787397f29c184c104c6a4735e6a726d1e5c6389/docs/rules/accessibility/no-aria-label-misuse.md)
As noted in the rule docs, there are conflicting resources on what elements should support these naming attributes. For now, this rule will operate under a relatively simple heuristic aimed to minimize false positives and target the most common misuse of `aria-label` we've seen, but there's definitely room for future improvements.
=> Introduce linter to prevent aria-label misuse

lib/erblint-github/linters/custom_helpers.rb
This change makes it so the linter offense message always includes a link to the rules documentation:
```
GitHub::Accessibility::ImageHasAlt:<img> should have an alt prop with meaningful text or an empty string for decorative images
Learn more at https://github.com/github/erblint-github#rules.
```
This ensures that consumers can find more information about the violation and are best equipped to fix it
=> Include link to rule docs in offense message

README.md, docs/rules/accessibility/avoid-both-disabled-and-aria-disabled.md, lib/erblint-github/linters/github/accessibility/avoid_both_disabled_and_aria_disabled.rb, test/linters/accessibility/avoid_both_disabled_and_aria_disabled_test.rb
This PR ports over a linter rule that raises when both `disabled` and `aria-disabled` are being set.
=> Add avoid both disabled and aria disabled rule

README.md, docs/rules/accessibility/avoid-both-disabled-and-aria-disabled.md, docs/rules/accessibility/iframe-has-title.md, docs/rules/accessibility/image-has-alt.md, docs/rules/accessibility/no-aria-label-misuse.md, docs/rules/accessibility/no-redundant-image-alt.md, lib/erblint-github/linters/github/accessibility/iframe_has_title.rb, test/linters/accessibility/iframe_has_title_test.rb
This PR ports over the `IframehasTitle` rule from dotcom including tests and documentation as part of the effort to port over accessibility rules. 
Additionally, this PR makes corrections to heading levels on our documentation pages.
=> Add iframe has title rule

README.md, docs/rules/accessibility/no-positive-tab-index.md, lib/erblint-github/linters/github/accessibility/no_positive_tab_index.rb, test/linters/accessibility/no_positive_tab_index_test.rb
This PR ports over the [no positive tabindex rule](https://github.com/github/github/blob/master/.erb-linters/accessibility/a11y_no_positive_tabindex.rb). 
Additionally, this adds missing test coverage and documentation regarding the rule.
=> Port over no positive tabindex rule

docs/rules/accessibility/no-redundant-image-alt.md
This PR updates the linter documentation with some additional helpful context, based on a [recent Slack discussion](https://github.slack.com/archives/C0FSWLQ0Y/p1643222107062600?thread_ts=1643220865.061500&cid=C0FSWLQ0Y).
=> Update redundant image rule documentation based on recent discussion

docs/rules/accessibility/no-aria-label-misuse.md
This PR updates the `NoAriaLabelMisuse` documentation to be more informative on why this is a discouarged pattern, and addresses violations that involve a tooltip. This also adds better examples of correct usage.
=> Update `NoAriaLabelMisuse` rule documentation

README.md, docs/rules/accessibility/no-title-attribute-counter.md, lib/erblint-github/linters/custom_helpers.rb, lib/erblint-github/linters/github/accessibility/no_title_attribute_counter.rb, test/custom_helpers_test.rb, test/linter_test_case.rb, test/linters/accessibility/no_title_attribute_counter_test.rb
Closes https://github.com/github/accessibility/issues/646, https://github.com/github/erblint-github/issues/18
`title` attribute is frequently used though it is inaccessible to many groups of users and hardly useful. This PR introduces a linter rule against it. This rule is implemented as a counter unlike the other rules, though we may consider converting other rules to counters too. This means that if a user wants to disable this rule on a file, they need to disable it with the exact offense count like:
```
<%# erblint:counter GitHub::Accessibility::FakeCounter 1 %>
```
instead of 
```
<%# erblint:disable GitHub::Accessibility::FakeLinter %>
```
The counter implementation is a workaround ported over from dotcom. `erb-lint` does not natively support granular rule disables so in dotcom …
=> Port over counter implementation and introduce linter against title attribute

docs/rules/accessibility/avoid-both-disabled-and-aria-disabled.md, docs/rules/accessibility/iframe-has-title.md, docs/rules/accessibility/image-has-alt.md, docs/rules/accessibility/no-aria-label-misuse-counter.md, docs/rules/accessibility/no-positive-tab-index.md, docs/rules/accessibility/no-redundant-image-alt.md, docs/rules/accessibility/no-title-attribute-counter.md
This PR adds references to recently created Primer Common pattern pages.
This also updates the markdown docs with a better heading structure, and moves emoji to the end.
```
```
=> docs: add recent primer common patterns links and better heading structures

docs/rules/accessibility/avoid-generic-link-text-counter.md, lib/erblint-github/linters/github/accessibility/avoid_generic_link_text_counter.rb, test/linters/accessibility/avoid_generic_link_text_counter_test.rb
Relates to: https://github.com/github/accessibility/issues/1291
@github/accessibility-reviewers before you review, please check the discussion in the linked issue :) 
This refines the generic linter text introduced in https://github.com/github/erblint-github/pull/32 based on internal discussions.
Currently, this linter will flag a link with generic text even if it has a descriptive accessible name set by `aria-labelledby` or `aria-label`. This is a _sometimes_ acceptable technique even if it may not be the most preferable, so we don't want to raise a flag because it could be a false positive. 
This updates the linter to not evaluate links with generic text that have ARIA attributes since linters should never raise false positives. One nuance we discussed is that when using ARIA to set a …
=> Refine generic link text linter logic

lib/erblint-github/linters/github/accessibility/avoid_generic_link_text_counter.rb, test/linters/accessibility/avoid_generic_link_text_counter_test.rb
I noticed a PR in dotcom with the text, `Learn more.` which this linter didn't catch because it only looks for case-insensitive exact string match.
This PR updates the linter to ignore punctuations and multiple whitespaces so we flag:
- `Learn more.`
- `Click     here!!! `
=> Make linter not count punctuation against match

lib/erblint-github/linters/github/accessibility/avoid_generic_link_text_counter.rb, test/linters/accessibility/avoid_generic_link_text_counter_test.rb
This PR fixes a bug where the punctuation of the visible text makes the `valid_accessible_name` check fail.
Example:
```
<a aria-label="Learn more about GitHub Sponsors.">Learn more.</a>
```
We have a check to make sure that the visible label is fully included inside of the accessible name text. Currently, we straight up take the visible text and see if it's included inside of the aria label. However, we don't strip the punctuation from the visible text before we do the check causing this example to incorrectly fail.
This PR makes it so we strip whitespace and punctuation from the visible label.
Thanks @jschnapper for pointing this out!
([Related Slack Context (GitHub Staff only)](https://github.slack.com/archives/C0FSWLQ0Y/p1657574649247259))
=> bug: Fixes AvoidGenericLinkText bug

README.md, docs/rules/accessibility/disabled-attribute-counter.md, lib/erblint-github/linters/github/accessibility/disabled_attribute_counter.rb, test/linters/accessibility/disabled_attribute_counter_test.rb
This PR migrates the accessibility rule `a11y_disabled_attribute` from dotcom to erblint-github
=> Migrate accessibility rule `a11y_disabled_attribute` from dotcom to erblint-github

README.md, docs/rules/accessibility/svg-has-accessible-text-counter.md, lib/erblint-github/linters/github/accessibility/svg_has_accessible_text_counter.rb, test/linters/accessibility/svg_has_accessible_text_counter_test.rb
This PR migrates the accessibility rule `a11y_svg_has_accessible_text` from dotcom to erblint-github
=> Migrate accessibility rule `a11y_svg_has_accessible_text` from dotcom to erblint-github

Gemfile.lock, erblint-github.gemspec
This PR updates the `erblint-github` gem version to `0.1.0` from `0.0.9` 
=> Update erblint-github gem version

README.md, docs/rules/accessibility/nested-interactive-elements-counter.md, lib/erblint-github/linters/github/accessibility/nested_interactive_elements_counter.rb, test/linters/accessibility/nested_interactive_elements_counter_test.rb
This PR migrates the accessibility rule `a11y_nested_interactive_elements` from dotcom to erblint-github
=> Migrate accessibility rule `a11y_nested_interactive_elements` from dotcom to erblint-github

README.md, docs/rules/accessibility/landmark-has-label-counter.md, lib/erblint-github/linters/github/accessibility/landmark_has_label_counter.rb, test/linters/accessibility/landmark_has_label_counter_test.rb
This PR migrates the accessibility rule `a11y_landmark_has_label` from dotcom to erblint-github
=> Migrate accessibility rule `a11y_landmark_has_label` from dotcom to erblint-github

Gemfile.lock, erblint-github.gemspec
This PR updates the `erblint-github` gem version to `0.1.1` from `0.1.0`
=> Update erblint-github gem to version `v0.1.1`

README.md
Adding documentation about how to disable ERB lint rules.
I'm marking this as experimental because this is an in-house way that GitHub has supported offense-level disables for years, but because it's not native to ERB lint, it should be used with caution.
=> Update README.md to describe how to disable rules

Gemfile.lock, erblint-github.gemspec
This PR updates the `erblint-github` gem version to `0.1.2` from `0.1.1`
- https://github.com/github/erblint-github/issues/48
=> Update erblint-github gem to version `v0.1.2`

README.md, docs/rules/accessibility/no-aria-hidden-on-focusable-counter.md, lib/erblint-github/linters/custom_helpers.rb, lib/erblint-github/linters/github/accessibility/nested_interactive_elements_counter.rb, lib/erblint-github/linters/github/accessibility/no_aria_hidden_on_focusable_counter.rb, test/linters/accessibility/no_aria_hidden_on_focusable_counter_test.rb
This new accessibility rule will flag when a focusable element has `aria-hidden="true"` set.  Why? One might set `aria-hidden="true"` to hide an element from assistive technologies, but if the element is still reachable by keyboard, it can cause confusion.
This is the ERB Lint equivalent of a [similar rule I PR-ed to `eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/no-aria-hidden-on-focusable.js).
=> rule: no-aria-hidden-on-focusable-elements

lib/erblint-github/linters/custom_helpers.rb, test/custom_helpers_test.rb, test/linters/accessibility/avoid_both_disabled_and_aria_disabled_test.rb
When the counter config is enabled, if there is no existing counter comment, let's suggest using `erblint:disable` and link to the docs to add inline disable natively, rather than suggesting adding a counter comment which is facing deprecation, now that we got inline disable support natively into `erblint`.
This PR additionally cleans up an unused method.
=> Suggest adding native disable instead of counter

README.md, docs/rules/accessibility/aria-label-is-well-formatted.md, lib/erblint-github/linters/github/accessibility/aria_label_is_well_formatted.rb, test/linters/accessibility/aria_label_is_well_formatted_test.rb
This PR introduces a new rule that flags downcased aria-label.
This is the ERBLint equivalent of the ESLint custom rule we introduced, [a11y-aria-label-is-well-formatted](https://github.com/github/eslint-plugin-github/blob/main/docs/rules/a11y-aria-label-is-well-formatted.md) a few weeks ago.
=> New rule that flags downcased aria-label

lib/erblint-github/linters/custom_helpers.rb, lib/erblint-github/linters/github/accessibility/aria_label_is_well_formatted.rb, test/linters/accessibility/aria_label_is_well_formatted_test.rb
When I was working on the update in our app (staff-only: https://github.com/github/github/pull/269682), I noticed there were some scenarios that were being flagged that shouldn't be.
I am updating the logic of `AriaLabelIsWellFormatted` to make sure it's not flagging what it's not supposed to. I am also cleaning up the logic to separate the starts with lowercase check + includes newline check. In addition, I added a test to make sure that excepting interpolated string works.
=> Update `AriaLabelIsWellFormatted` logic

docs/rules/accessibility/aria-label-is-well-formatted.md
Noticed a small typo in the anchor examples of the docs:
```html
<a href="https://github.com/shopify/erb-lint"> aria-label="Shopify/erb-lint on GitHub"></a>
```
However, the anchor is closed before the aria-label attribute, so I changed it to:
```html
<a href="https://github.com/shopify/erb-lint" aria-label="Shopify/erb-lint on GitHub"></a>
```
=> Fix small typo in aria-label-is-well-formatted.md

README.md, docs/counter-migration-guide.md, lib/erblint-github/linters/custom_helpers.rb, lib/erblint-github/linters/github/accessibility/avoid_both_disabled_and_aria_disabled.rb, lib/erblint-github/linters/github/accessibility/avoid_generic_link_text.rb, lib/erblint-github/linters/github/accessibility/disabled_attribute.rb, lib/erblint-github/linters/github/accessibility/iframe_has_title.rb, lib/erblint-github/linters/github/accessibility/image_has_alt.rb, lib/erblint-github/linters/github/accessibility/link_has_href.rb, lib/erblint-github/linters/github/accessibility/nested_interactive_elements.rb, lib/erblint-github/linters/github/accessibility/no_aria_hidden_on_focusable.rb, lib/erblint-github/linters/github/accessibility/no_aria_label_misuse.rb, lib/erblint-github/linters/github/accessibility/no_positive_tab_index.rb, lib/erblint-github/linters/github/accessibility/no_redundant_image_alt.rb, lib/erblint-github/linters/github/accessibility/no_title_attribute.rb, lib/erblint-github/linters/github/accessibility/svg_has_accessible_text.rb, test/custom_helpers_test.rb, test/linters/accessibility/avoid_both_disabled_and_aria_disabled_test.rb, test/linters/accessibility/avoid_generic_link_text_test.rb, test/linters/accessibility/disabled_attribute_test.rb, test/linters/accessibility/iframe_has_title_test.rb, test/linters/accessibility/image_has_alt_test.rb, test/linters/accessibility/link_has_href_test.rb, test/linters/accessibility/nested_interactive_elements_test.rb, test/linters/accessibility/no_aria_label_misuse_test.rb, test/linters/accessibility/no_positive_tab_index_test.rb, test/linters/accessibility/no_redundant_image_alt_test.rb, test/linters/accessibility/no_title_attribute_test.rb, test/linters/accessibility/svg_has_accessible_text_test.rb
Fixes: https://github.com/github/erblint-github/issues/74
This PR completely removes the counter-system related code, which was moved to deprecation status in v0.2.0. 
We've supported enabling the counter system on a per rule basis to [ease migration](https://github.com/github/erblint-github/blob/main/docs/counter-migration-guide.md) but now that we're a few versions in, let's completely deprecate it.
=> chore: remove counter-related code.

lib/erblint-github/linters/custom_helpers.rb
This PR _temporarily_ introduces back the `counter_correct?` helper which was removed in a recent PR.
One of our project pulls in both `erblint-github` and `primer_view_components`. The latter has a custom rule which pulls in the `counter_correct?` helper from this gem.
This means that projects that use `primer_view_components` are blocked on upgrading `erblint_github` due to the lint rule in `primer_view_components` depending on this `counter_correct?` helper.
I've since removed the dependency on `erblint-github` from `primer_view_components` in https://github.com/primer/view_components/pull/2067, but until there's a new version of `primer_view_components` for consumers, I'd like to temporarily keep this custom helper in this gem.
=> Temporarily introduce back counter_correct? helper

.erb-lint.yml, .erb-linters/linters.rb, test/linter_test_case.rb, test/recommended_setup_works_test.rb
This PR adds test coverage for the setup that we recommend in our README.
=> Add test to ensure recommended setup works

config/accessibility.yml
The `NoUnusedDisable` rule should be on by default in our recommended configs.
This rule flags when a disable comment is no longer necessary.
=> Update accessibility.yml recommended configs.

config/accessibility.yml, docs/rules/accessibility/no-visually-hidden-interactive-elements.md, lib/erblint-github/linters/github/accessibility/no_visually_hidden_interactive_elements.rb, test/linters/accessibility/no_visually_hidden_interactive_elements_test.rb, test/recommended_setup_works_test.rb
This rule checks that interactive elements are not visually hidden.  
Visually hiding content can be useful when you want to provide information specifically to screen reader users or other assistive technology users while keeping content hidden from sighted users.
-  does not take into account `as` prop since erb files do not have an `as` prop
-  does not allow for className to be configured. We only check for the `sr-only` class.
=> Create rule: no-visually-hidden-interactive-element

Gemfile.lock, bin/erblint-disable, erblint-github.gemspec
Related to https://github.com/github/accessibility/issues/3825.
This script will be able to be run from any project that includes it by running `bundle exec erblint-disable ...`.
Will need to follow up with PRs to dotcom, classroom and education-web to remove the script that is currently in those repos.
=> Add `erblint-disable` script from dotcom and friends.

docs/rules/accessibility/navigation-has-label.md
Making clear that `aria-labelledby` to a heading is preferred where possible.
=> Update navigation-has-label docs

docs/rules/accessibility/no-title-attribute.md, lib/erblint-github/linters/github/accessibility/no_title_attribute.rb, test/linters/accessibility/no_title_attribute_test.rb
Fixes: https://github.com/github/erblint-github/issues/108
It seems reasonable to not flag the `<link>` tag given it's NOT user-facing and [title has special semantics on the link element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#title) to define a default or an alternate stylesheet.
=> Don't flag `title` on link tag

.github/workflows/auto-approve-and-merge.yml
Effort to reduce FR burden by auto approving and merging dependabot updates that pass all checks. We can always review these when it's time to cut a release too.
=> Auto approve and merge dependabot updates

README.md, lib/erblint-github/linters/github/accessibility/no_visually_hidden_interactive_elements.rb, test/linters/accessibility/no_visually_hidden_interactive_elements_test.rb
Fixes: https://github.com/github/accessibility/issues/4848
I saw a few unexpected elements being flagged with our new rule, `no-visually-hidden-interctive-elements`. I added a test case `test_does_not_warn_on_unexpected_elements` which fails with the current code on main.
I think the logic we have right now try to determine if an interactive element is nested inside an sr-only isn't quite complete. I suggest we simplify the logic for now to only flag interactive elements with `sr-only`.
=> Simplify no-visually-hidden-interactive-elements and fix bug

lib/erblint-github/linters/custom_helpers.rb
Fixes: https://github.com/github/erblint-github/security/code-scanning/2
Fixes: https://github.com/github/erblint-github/security/code-scanning/1
I must have ported this file over from dotcom, but this function is not used in any of our rules, and is raising a code scanning alert. 
Let's remove this!
=> Remove unused helper method

.github/workflows/ci.yml
- pin an external Action to a specific hash (which in this case is what `setup-ruby` has versioned as v1.190.0)
- explicitly specify permissions
=> Tighten up some auto-reported security issues
